#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
B="$(printf '\033[1;34m')"
C="$(printf '\033[1;36m')"
W="$(printf '\033[1;37m')"

banner() {

		cat <<- EOF
		${Y}    ------------------------
		${C}    |     Liquid-Linux     |
		${G}    ------------------------
	EOF

	echo -e "${G}     Virtual linux client for Termux"${W}
	echo -e "     Powered by ${G}U${R}b${Y}u${C}n${B}t${G}u ${R}M${Y}o${B}d\n\n"${W}

}

package() {
    echo -e "${R} [${W}-${R}]${C} Purging packages..."${W}
    proot-distro remove liquid && proot-distro clear-cache
    rm -rf $PREFIX/bin/liquid
    sed -i '/pulseaudio --start --exit-idle-time=-1/d' ~/.sound
    sed -i '/pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1/d' ~/.sound
    echo -e "${R} [${W}-${R}]${C} Purging Completed !"${W}

}

banner
package
